### ISSUE TITLE
MOSAIC NOT DISPLAYING FOR ME

### ISSUE THREAD

**Issue by spmadrid** [Molkobain/itop-portal-mosaic-service-catalog#1]
Hi,

I Can't seem to make the MOSAIC as the default view.

I followed your instruction in uploading it to extension and running setup.
I am not sure if I am missing something that is quite obvious.

I didn't seem to follow your guide to customize portal.
I am not sure if mine is customized or not.
What do you mean by customized?

Where can I check PORTAL ID and SERVICE CATALOG BRICK?

Thanks.

**Comment by Molkobain** [comment]
Hello!

Could you tell me which version of iTop your are running?
Also, can you open the about box (it's in the same menu as the logoff button on the administration console) and send me the "support information"? It would help to see if you are using the enhanced portal and if the module is installed.

If you are using the standard enhanced portal, there is no need for you to customize any thing, it should work out of the box.

During the setup, on one of the last steps, you should see the module's name and check it.

**Comment by spmadrid** [comment]
Hi Molobain,

iTop version 2.6.1-4463
[about.txt](https://github.com/Molkobain/itop-portal-mosaic-service-catalog/files/3589410/about.txt)

I'm so sorry I've wasted your time, I thought I already checked that tick box, but it seems I'm so sleepy last night and didn't recognize that I didn't.

It's working now with no issues.
Thanks to you my portal now are so user-friendly
![image](https://user-images.githubusercontent.com/5051669/64519826-7d3f5a80-d327-11e9-9a2f-5625b81c8029.png)

**Comment by Molkobain** [comment]
Glad to see it works fine. Enjoy! 😊
